# -*- coding: utf-8 -*-
"""grapeleaf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Eq5GhcfPFxsZ5yODkZFYftb7S1kyWsw
"""

from sklearn.model_selection import train_test_split
import shutil
import os # Added this line for os.path.join, os.makedirs, os.listdir, os.rmdir

# Assuming base_dir has been correctly determined in the previous cell
# For this example, let's re-state it based on the kernel state if it was not printed.
# In the last execution, the base_dir was likely set to '/content/dataset/Black_rot2'
# However, the previous cell raised a FileNotFoundError because 'train', 'val', 'test'
# were not found under this base_dir. We need to create them.

# Check if base_dir is defined. If not, it means the previous cell that was supposed to define it either didn't run
# or the kernel was restarted. We need to establish base_dir and extract_path.
if 'base_dir' not in globals() and 'base_dir' not in locals():
    print("Warning: 'base_dir' was not found in the current environment. This often happens if the kernel was restarted or a previous cell was not executed.")
    print("Attempting to re-establish 'extract_path' and 'base_dir' based on common patterns.")

    # Re-establish extract_path
    if 'extract_path' not in globals() and 'extract_path' not in locals():
        print("Warning: 'extract_path' also not found. Assuming '/content/dataset' as the default extraction path.")
        extract_path = '/content/dataset'
        # Removed the note here as the error below is more explicit
    else:
        # If extract_path exists, use it.
        pass

    # Try to determine base_dir based on extract_path
    potential_base_dir = os.path.join(extract_path, 'Black_rot2')
    if os.path.isdir(potential_base_dir):
        base_dir = potential_base_dir
        print(f"Re-established base_dir as: {base_dir}")
    else:
        # Instead of falling back to extract_path, raise an error to ensure extraction has occurred
        raise FileNotFoundError(
            f"Expected dataset directory '{potential_base_dir}' not found. "
            "Please ensure the dataset has been extracted by running the previous cell (JoY_t8oHKehv) first."
        )

# Now, base_dir should be defined and point to '/content/dataset/Black_rot2'. The original code can proceed.

# Define the new train, val, test directories
new_train_dir = os.path.join(base_dir, "train")
new_val_dir = os.path.join(base_dir, "val")
new_test_dir = os.path.join(base_dir, "test")

# Create these directories if they don't exist
os.makedirs(new_train_dir, exist_ok=True)
os.makedirs(new_val_dir, exist_ok=True)
os.makedirs(new_test_dir, exist_ok=True)

# Get a list of all class directories (subfolders) within the base_dir
class_names = [d for d in os.listdir(base_dir) if os.path.isdir(os.path.join(base_dir, d)) and not d.startswith(('train', 'val', 'test'))]

# Add an explicit check for found classes
if not class_names:
    raise RuntimeError(
        f"No class subdirectories found in '{base_dir}'. "
        "This likely means the dataset was extracted but does not contain the expected class folders directly within it. "
        "Please verify the structure of the extracted dataset."
    )

print(f"Found {len(class_names)} classes: {class_names}")

for class_name in class_names:
    class_path = os.path.join(base_dir, class_name)
    images = [os.path.join(class_path, img) for img in os.listdir(class_path) if img.lower().endswith(('.png', '.jpg', '.jpeg'))]

    # Split data into train (70%), validation (15%), test (15%)
    train_images, test_val_images = train_test_split(images, test_size=0.3, random_state=42)
    val_images, test_images = train_test_split(test_val_images, test_size=0.5, random_state=42) # 0.5 of 30% is 15%

    # Create class subdirectories in new train/val/test folders
    os.makedirs(os.path.join(new_train_dir, class_name), exist_ok=True)
    os.makedirs(os.path.join(new_val_dir, class_name), exist_ok=True)
    os.makedirs(os.path.join(new_test_dir, class_name), exist_ok=True)

    # Move images to their respective directories
    for img_path in train_images:
        shutil.move(img_path, os.path.join(new_train_dir, class_name, os.path.basename(img_path)))
    for img_path in val_images:
        shutil.move(img_path, os.path.join(new_val_dir, class_name, os.path.basename(img_path)))
    for img_path in test_images:
        shutil.move(img_path, os.path.join(new_test_dir, class_name, os.path.basename(img_path)))

    # Remove the original class directory if it's now empty
    if not os.listdir(class_path): # Check if directory is empty after moving images
        os.rmdir(class_path)

print("Dataset successfully restructured into train, validation, and test directories.")

# Now update the train_dir, val_dir, test_dir to point to the newly created folders
train_dir = new_train_dir
val_dir = new_val_dir
test_dir = new_test_dir

print(f"Updated train_dir: {train_dir}")
print(f"Updated val_dir: {val_dir}")
print(f"Updated test_dir: {test_dir}")

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import zipfile
import os

#zip file
zip_file='/content/drive/MyDrive/Black_rot2.zip'
extract_path = '/content/dataset'

# Ensure the extract_path exists
os.makedirs(extract_path, exist_ok=True)

# Unzip the dataset if not already extracted
target_extracted_dir = os.path.join(extract_path, 'Black_rot2')
if not os.path.exists(target_extracted_dir):
    print(f"Extracting {zip_file} to {extract_path}...")
    with zipfile.ZipFile(zip_file, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("Extraction complete.")
else:
    print(f"Dataset already extracted to {target_extracted_dir}.")

# The base_dir for the *unsplit* class images is now known:
base_dir = target_extracted_dir
print(f"Base directory for raw classes (unsplit) identified as: {base_dir}")

# IMPORTANT: The next step is to split this raw data into train, val, test.
# This is handled by the data splitting cell (mjUeDB5mw_tn).
# We now rely on 'train_dir', 'val_dir', 'test_dir' being set by that cell's execution *after* this one.

# Check if train_dir, val_dir, test_dir are defined from previous (splitting) cell execution
if 'train_dir' not in globals() or 'val_dir' not in globals() or 'test_dir' not in globals():
    # If the user runs this cell directly after kernel restart, and the splitting cell hasn't run.
    # Provide a clear instruction.
    raise RuntimeError(
        "Error: 'train_dir', 'val_dir', or 'test_dir' not found. "
        "Please ensure the data splitting cell (mjUeDB5mw_tn) is executed *after* this cell "
        "to prepare the dataset for training."
    )

# Use the train_dir, val_dir, test_dir set by the data splitting cell
print(f"Using train_dir: {train_dir}")
print(f"Using val_dir: {val_dir}")
print(f"Using test_dir: {test_dir}")

# Image parameters
IMG_SIZE = 224
BATCH_SIZE = 16

# Data generators (rescaling + augmentation)
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

# Initialize data generators and add error handling
try:
    train_data = train_datagen.flow_from_directory(
        train_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='categorical'
    )

    val_data = val_datagen.flow_from_directory(
        val_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='categorical'
    )

    test_data = test_datagen.flow_from_directory(
        test_dir,
        target_size=(IMG_SIZE, IMG_SIZE),
        batch_size=BATCH_SIZE,
        class_mode='categorical',
        shuffle=False
    )
except Exception as e:
    raise RuntimeError(
        f"Error initializing ImageDataGenerators. This could be due to empty or non-existent directories. "
        f"Please check if '{train_dir}', '{val_dir}', and '{test_dir}' exist and contain images. "
        f"Original error: {e}"
    )

if train_data.num_classes == 0:
    raise ValueError(
        f"train_data.num_classes is 0. This means no images were found in '{train_dir}' "
        "for any classes. Please ensure the data splitting cell (mjUeDB5mw_tn) "
        "successfully created and populated the train, val, and test directories with images "
        f"from the base directory '{base_dir}'."
    )

# Build CNN Model
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(train_data.num_classes, activation='softmax')
])

# Compile
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Train
history = model.fit(
    train_data,
    validation_data=val_data,
    epochs=70
)

# Save model
model.save("leaf_disease_model.h5")

# Evaluate on test data
test_loss, test_acc = model.evaluate(test_data)
print(f"Test Accuracy: {test_acc}")

# Predictions
predictions = model.predict(test_data)
y_pred = np.argmax(predictions, axis=1)
y_true = test_data.classes

# Classification report
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=test_data.class_indices.keys()))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_true, y_pred))

# Plot accuracy graph
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.title("Accuracy Graph")
plt.show()

"""## Model Performance Dashboard"""

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Re-calculate predictions and true labels (ensure variables are still in scope)
# If the kernel was reset, you might need to re-run the previous cell up to this point.
if 'test_data' not in locals() or 'model' not in locals():
    print("Warning: 'test_data' or 'model' not found. Please ensure the model training cell was run.")
    # In a real scenario, you might add code here to reload the model and test_data
    # For this exercise, we assume the variables are still available from the previous run.
    # Example of how you might re-load if necessary:
    # from tensorflow.keras.models import load_model
    # model = load_model("leaf_disease_model.h5")
    # You would also need to re-create test_data if it wasn't available.

    # For robustness, let's try to infer from the existing notebook state.
    # Assuming `test_data` is available from the last executed cell
    # This part is illustrative and assumes the environment retains state.
    pass

# Ensure these variables are available from the previous execution
if 'test_data' in locals() and 'model' in locals():
    predictions = model.predict(test_data)
    y_pred = np.argmax(predictions, axis=1)
    y_true = test_data.classes
    class_labels = list(test_data.class_indices.keys())

    # Plot Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_labels, yticklabels=class_labels)
    plt.title('Confusion Matrix')
    plt.ylabel('True Label')
    plt.xlabel('Predicted Label')
    plt.show()

    # Display Classification Report in a more readable format
    report = classification_report(y_true, y_pred, target_names=class_labels, output_dict=True)
    print("\n--- Classification Report Summary ---")
    for label, metrics in report.items():
        if isinstance(metrics, dict):
            print(f"Class: {label}")
            print(f"  Precision: {metrics['precision']:.2f}")
            print(f"  Recall: {metrics['recall']:.2f}")
            print(f"  F1-Score: {metrics['f1-score']:.2f}")
        elif label in ['accuracy', 'macro avg', 'weighted avg']:
            print(f"\n{label.replace('_', ' ').title()}:")
            if label == 'accuracy':
                print(f"  Accuracy: {metrics:.2f}")
            else:
                print(f"  Precision: {metrics['precision']:.2f}")
                print(f"  Recall: {metrics['recall']:.2f}")
                print(f"  F1-Score: {metrics['f1-score']:.2f}")
    print("-------------------------------------")

    # Re-display the accuracy graph for quick reference in the dashboard context
    if 'history' in locals():
        plt.figure(figsize=(8, 6))
        plt.plot(history.history['accuracy'], label='Train Accuracy')
        plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
        plt.legend()
        plt.title("Model Accuracy Over Epochs")
        plt.xlabel("Epoch")
        plt.ylabel("Accuracy")
        plt.grid(True)
        plt.show()
    else:
        print("Warning: 'history' object not found. Accuracy graph cannot be re-plotted.")
else:
    print("Cannot generate dashboard. Required variables (test_data, model, history) are not available.")

"""## Make a Prediction on a New Image

Upload a grape leaf image to classify it as healthy or detect the stage of black rot.
"""

from google.colab import files
from tensorflow.keras.preprocessing import image
import numpy as np # Added for np.expand_dims
import matplotlib.pyplot as plt # Added for plt.imshow, plt.show
from tensorflow.keras.models import load_model # Ensure load_model is available

# Image parameters - crucial for prediction
IMG_SIZE = 224

# Ensure model is loaded (if not already from previous execution)
if 'model' not in locals():
    try:
        model = load_model("leaf_disease_model.h5") # Corrected model filename
        print("Model 'leaf_disease_model.h5' loaded successfully.")
    except Exception as e:
        print(f"Error loading model: {e}. Please ensure 'leaf_disease_model.h5' exists and the training cell was run.")

# Get class names from the train_data generator (assuming it's still available)
# If not, you might need to manually define them or re-run the data loading part
if 'train_data' in locals():
    class_names = list(train_data.class_indices.keys())
else:
    print("Warning: train_data not found. Attempting to infer class names from existing model output or default.")
    # Fallback if train_data is not in scope - adjust if your model has different classes
    class_names = ['Grape___healthy', 'Stage1_Early_Infection', 'Stage2_Lesion_Expansion', 'Stage3_Advanced_Infection', 'Stage4_Terminal_Incurable']

def predict_image(img_path):
    img = image.load_img(img_path, target_size=(IMG_SIZE, IMG_SIZE))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0) / 255.0  # Rescale to 0-1

    predictions = model.predict(img_array)
    predicted_class_index = np.argmax(predictions)
    predicted_class = class_names[predicted_class_index]
    confidence = np.max(predictions) * 100

    plt.imshow(img)
    plt.title(f"Predicted: {predicted_class} (Confidence: {confidence:.2f}%) Kishan)")
    plt.axis('off')
    plt.show()
    return predicted_class, confidence

print("Please upload an image for prediction:")
uploaded = files.upload()

for fn in uploaded.keys():
    print(f"User uploaded file \"{fn}\"")
    predict_image(fn)

from google.colab import drive
drive.mount('/content/drive')